apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kibana
  labels:
    k8s-app: kibana
spec:
  selector:
    k8s-app: kibana
  ports:
  - name: http
    port: 5601
  type: LoadBalancer
